/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen 1.5.1
 **/

#ifndef __unitree_asr_AsrTextMessage_hpp__
#define __unitree_asr_AsrTextMessage_hpp__

#include <lcm/lcm_coretypes.h>

#include <string>

namespace unitree_asr
{

class AsrTextMessage
{
    public:
        int64_t    timestamp;

        /**
         * 时间戳
         */
        std::string text;

        /**
         * ASR识别的文本内容
         */
        float      confidence;

        /**
         * 置信度
         */
        std::string language;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "AsrTextMessage"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int AsrTextMessage::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int AsrTextMessage::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int AsrTextMessage::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t AsrTextMessage::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* AsrTextMessage::getTypeName()
{
    return "AsrTextMessage";
}

int AsrTextMessage::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* text_cstr = const_cast<char*>(this->text.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &text_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->confidence, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* language_cstr = const_cast<char*>(this->language.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &language_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int AsrTextMessage::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    int32_t __text_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__text_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__text_len__ > maxlen - pos) return -1;
    this->text.assign(
        static_cast<const char*>(buf) + offset + pos, __text_len__ - 1);
    pos += __text_len__;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->confidence, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    int32_t __language_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__language_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__language_len__ > maxlen - pos) return -1;
    this->language.assign(
        static_cast<const char*>(buf) + offset + pos, __language_len__ - 1);
    pos += __language_len__;

    return pos;
}

int AsrTextMessage::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += this->text.size() + 4 + 1;
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += this->language.size() + 4 + 1;
    return enc_size;
}

uint64_t AsrTextMessage::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0x7597f270a2f40a37LL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
